### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [earowang/sugrrants#11]
Hello @earowang 

I am a graphic designer. I contribute to open source software by designing logos in free time. I designed a logo for suggrants. What do you think?

![suggrants](https://user-images.githubusercontent.com/36298335/42735431-5a9aa38e-885c-11e8-805f-ba12a218f19a.jpg)

**Comment by earowang** [comment]
Hi there,

Thank you so much for making the logo. But **sugrrants** had a logo featuring "sugar ant" a while ago, which I haven't yet put to the public.

Much appreciated.
