### ISSUE TITLE
Is the default start of `facet-calendar` really Sunday?

### ISSUE THREAD

**Issue by DaveParr** [earowang/sugrrants#15]
In the documentation, the facet defines Sunday (`7`) as the start of the week: https://github.com/earowang/sugrrants/blob/c108e8a59641a8b974c04baa213c7308ab4922e8/R/facet-calendar.R#L10

However, the code indicates that the default value is actually `1`, which is Monday?
https://github.com/earowang/sugrrants/blob/c108e8a59641a8b974c04baa213c7308ab4922e8/R/facet-calendar.R#L39

My local implementations seem to confirm this.

Ignoring that, really love this function, and the package in general. Thanks for the work 😄

**Comment by earowang** [comment]
The default is Monday. Thanks for catching it.

**Comment by DaveParr** [comment]
No problem, loving all this tidyverts tsibble work. Miles better than my old approaches :)
