### ISSUE TITLE
Error returned in example for:    frame_calendar()

### ISSUE THREAD

**Issue by sfd99** [earowang/sugrrants#16]
calendar_df <- pedestrian %>%
   filter(Sensor_ID == 13, Year == 2016) %>%
   frame_calendar(x = Time, y = Hourly_Counts, date = Date, nrow = 4)
filter: removed 69972 out of 78755 rows (89%)

Error in loadNamespace(name) : there is no package called ‘tsibble’

**Comment by earowang** [comment]
Thanks for reporting this. It is an unexpected error message.
