### ISSUE TITLE
Examples fail with dev ggplot2

### ISSUE THREAD

**Issue by hadley** [earowang/sugrrants#8]
...
    >    p1 <- calendar_df %>% 
    +      ggplot(aes(x = .Time, y = .Hourly_Counts, group = Date)) +
    +      geom_line()
    >    prettify(p1, size = 3, label.padding = unit(0.15, "lines"))
    >    
    >    # use in conjunction with group_by()
    >    grped_calendar <- pedestrian %>% 
    +      filter(Year == "2017", Month == "March") %>% 
    +      group_by(Sensor_Name) %>% 
    +      frame_calendar(
    +        x = Time, y = Hourly_Counts, date = Date, sunday = TRUE
    +      )
    >    
    >    p2 <- grped_calendar %>% 
    +      ggplot(aes(x = .Time, y = .Hourly_Counts, group = Date)) +
    +      geom_line() +
    +      facet_wrap(~ Sensor_Name, nrow = 2)
    Error in grouped_indices_grouped_df_impl(.data) : 
      Need at least one column for `hash()`
    Calls: %>% ... group_indices.grouped_df -> grouped_indices_grouped_df_impl
    Execution halted

Can you please help us figure out what's gone wrong?

**Comment by mitchelloharawild** [comment]
We can resolve this, although I don't know why `ggplot.grouped_df` needs to add `.group` to the data. Shouldn't this belong in a fortify method for `grouped_df`? It's easy to produce a problematic use-case for this.

```r
iris %>%
  rename(.group = Sepal.Length) %>%
  group_by(Species) %>% 
  ggplot(aes(x=.group, y=Sepal.Width)) + 
  geom_point()
```

**Comment by hadley** [comment]
Oooooooooooooooooh  (and it doesn't any more; see https://github.com/tidyverse/ggplot2/issues/2578 for context). Thanks for figuring this out!
